ogen-go/ogen

_testdata/err_oneof_explicit.yaml
_testdata/err_oneof_implicit.yaml
gen_test.go
internal/gen/schema_gen.go

fix(gen): remove nil pointer dereference

---

dsl.go
dsl_test.go

This PR introduces a fluent interface to ease construction and manipulation of the specification by code.

[Feature] DSL

---

README.md
dsl.go
spec.go

* Examples
* Tags
Fix #83
Fix #70

feat: add missing fields

---

_testdata/sample.json
examples/ex_ent/oas_json_gen.go
examples/ex_firecracker/oas_json_gen.go
examples/ex_github/oas_json_gen.go
examples/ex_gotd/oas_json_gen.go
examples/ex_k8s/oas_json_gen.go
examples/ex_manga/oas_json_gen.go
examples/ex_petstore/oas_json_gen.go
examples/ex_petstore_expanded/oas_json_gen.go
examples/ex_telegram/oas_json_gen.go
examples/ex_tinkoff/oas_json_gen.go
gen/_template/json/encoders_generic.tmpl
internal/sample_api/oas_json_gen.go
internal/sample_api/oas_schemas_gen.go
internal/sample_err/oas_json_gen.go
json_test.go

fix(gen): optional encoding

---

_testdata/sample.json
examples/ex_github/oas_json_gen.go
gen/_template/json/decode.tmpl
gen/_template/json/encoders_generic.tmpl
internal/sample_api/oas_json_gen.go
internal/sample_api/oas_schemas_gen.go
internal/sample_api/oas_validators_gen.go
json_integration_test.go
json_test.go
validate_test.go

fix(gen): optional/nullable array JSON encoding

---

gen/schema_gen.go

fix(gen): discriminator inference by unique fields

---

_testdata/positive/sample.json
e2e_test.go
examples/ex_ent/oas_res_dec_gen.go
examples/ex_github/oas_json_gen.go
examples/ex_github/oas_res_dec_gen.go
examples/ex_k8s/oas_json_gen.go
examples/ex_k8s/oas_res_dec_gen.go
examples/ex_manga/oas_res_dec_gen.go
examples/ex_petstore/oas_res_dec_gen.go
gen/_template/json/decode.tmpl
internal/sample_api/oas_client_gen.go
internal/sample_api/oas_handlers_gen.go
internal/sample_api/oas_json_gen.go
internal/sample_api/oas_res_dec_gen.go
internal/sample_api/oas_res_enc_gen.go
internal/sample_api/oas_router_gen.go
internal/sample_api/oas_schemas_gen.go
internal/sample_api/oas_server_gen.go
internal/sample_api/oas_validators_gen.go
internal/techempower/oas_res_dec_gen.go
json_test.go

fix(gen): call Decode on Alias instead of inlining decoder

---

_testdata/positive/test_empty_property_name.yaml
gen/schema_gen.go
gen_test.go

fix(gen): add fallback name generation if property name is empty

---

cmd/jschemagen/main.go
gen/_template/json.tmpl
gen/_template/jsonschema.tmpl
gen/_template/schemas.tmpl
gen/_template/validators.tmpl
gen/_testdata/jsonschema/defs.json
gen/_testdata/jsonschema/platform.json
gen/gen_schema.go
gen/gen_schema_test.go

feat: separate jsonschema generator to GenerateSchema function

---

_testdata/positive/test_property_ref.json
gen/gen_schema.go
gen/schema_gen.go
internal/oas/parser/parser.go
internal/oas/parser/ref.go
internal/oas/parser/resolver.go
jsonpointer/errors.go
jsonpointer/errors_test.go
jsonpointer/jsonpointer.go
jsonpointer/jsonpointer_test.go
jsonpointer/split.go
jsonschema/resolver.go
spec.go

feat: initial support for JSON Schema compatible reference resolver

---

_testdata/positive/test_format.json
examples/ex_test_format/oas_client_gen.go
examples/ex_test_format/oas_faker_gen.go
examples/ex_test_format/oas_handlers_gen.go
examples/ex_test_format/oas_json_gen.go
examples/ex_test_format/oas_req_dec_gen.go
examples/ex_test_format/oas_req_enc_gen.go
examples/ex_test_format/oas_res_dec_gen.go
examples/ex_test_format/oas_res_enc_gen.go
examples/ex_test_format/oas_router_gen.go
examples/ex_test_format/oas_schemas_gen.go
examples/ex_test_format/oas_server_gen.go
examples/ex_test_format/oas_unimplemented_gen.go
examples/ex_test_format/oas_validators_gen.go
gen/ir/json.go
gen/ir/type.go
gen/schema_gen_primitive.go
json/time.go
json/unix.go
json/unix_test.go

feat(gen): add unix timestamps support

---

_testdata/positive/sample.json
examples/ex_github/oas_faker_gen.go
examples/ex_github/oas_schemas_gen.go
examples/ex_github/oas_test_examples_gen_test.go
examples/ex_openapi/output.gen.go
gen/_template/json/encoders_map.tmpl
gen/_template/json/encoders_struct.tmpl
gen/ir/type.go
gen/schema_gen.go
internal/sample_api/oas_client_gen.go
internal/sample_api/oas_faker_gen.go
internal/sample_api/oas_handlers_gen.go
internal/sample_api/oas_json_gen.go
internal/sample_api/oas_res_dec_gen.go
internal/sample_api/oas_res_enc_gen.go
internal/sample_api/oas_router_gen.go
internal/sample_api/oas_schemas_gen.go
internal/sample_api/oas_server_gen.go
internal/sample_api/oas_test_examples_gen_test.go
internal/sample_api/oas_unimplemented_gen.go
json_test.go
jsonschema/parser.go
jsonschema/raw_schema.go
jsonschema/schema.go
spec.go
spec_backcomp.go

feat(gen): support explicit additionalProperties = false

---

cmd/jschemagen/main.go
examples/ex_openapi/output.gen.go
examples/generate.go
gen/ir/constructors.go
gen/schema_gen.go

feat(jschemagen): improve UX

---

cmd/ogen/main.go
examples/generate.go
ogen.go

refactor(ogen): pass schema path as first position argument

---

json/equal.go
json/equal_test.go

feat(json): add json value comparator

---

_testdata/positive/sample.json
_testdata/positive/superset.json
e2e_test.go
gen/_template/parameter_decode.tmpl
gen/_template/parameter_encode.tmpl
gen/gen_parameters.go
gen/templates.go
gen_test.go
internal/sample_api/oas_client_gen.go
internal/sample_api/oas_faker_gen.go
internal/sample_api/oas_handlers_gen.go
internal/sample_api/oas_json_gen.go
internal/sample_api/oas_parameters_gen.go
internal/sample_api/oas_response_decoders_gen.go
internal/sample_api/oas_response_encoders_gen.go
internal/sample_api/oas_router_gen.go
internal/sample_api/oas_schemas_gen.go
internal/sample_api/oas_server_gen.go
internal/sample_api/oas_test_examples_gen_test.go
internal/sample_api/oas_unimplemented_gen.go
openapi/parameter.go
openapi/parser/parse_header.go
openapi/parser/parse_mediatype.go
openapi/parser/parse_parameter.go

feat(gen): parameter content

---

cmd/ogen/main.go
gen/external.go
gen/generator.go
jsonschema/external.go
jsonschema/parser.go
jsonschema/parser_settings.go
jsonschema/parser_test.go
jsonschema/resolve.go
jsonschema/resolve_test.go
jsonschema/resolver.go
openapi/parser/parser.go
openapi/parser/settings.go
tools/sgcollector/worker.go

feat(jsonschema): initial remote references support

---

gen/gen_contents.go

fix(gen): use ordered iteration when generating contents

---

_testdata/positive/format_gen.json
examples/ex_test_format/oas_client_gen.go
examples/ex_test_format/oas_faker_gen.go
examples/ex_test_format/oas_handlers_gen.go
examples/ex_test_format/oas_json_gen.go
examples/ex_test_format/oas_parameters_gen.go
examples/ex_test_format/oas_request_decoders_gen.go
examples/ex_test_format/oas_request_encoders_gen.go
examples/ex_test_format/oas_response_decoders_gen.go
examples/ex_test_format/oas_response_encoders_gen.go
examples/ex_test_format/oas_router_gen.go
examples/ex_test_format/oas_schemas_gen.go
examples/ex_test_format/oas_server_gen.go
examples/ex_test_format/oas_unimplemented_gen.go
examples/ex_test_format/oas_validators_gen.go
gen/ir/json.go
gen/ir/type.go
gen/schema_gen_primitive.go
json/unix.go
json/unix_str.go
json/unix_str_test.go

feat(gen): support integer unix format

---

jsonschema/enum.go
jsonschema/enum_test.go
jsonschema/num.go
jsonschema/raw_value.go

fix(jsonschema): marshal `Enum` and `Num` correctly

---

gen/ir/operation.go

fix(gen): generate header encoders for 'convenient errors'

---

examples/ex_tinkoff/oas_security_gen.go
gen/_template/security.tmpl

Verify auth scheme and populate correct token value.

feat(gen): improve bearer security template

---

_testdata/positive/allOf.yml
gen/schema_gen_sum.go
gen_bench_test.go
internal/integration/all_of_test.go
internal/integration/test_allof/oas_client_gen.go
internal/integration/test_allof/oas_handlers_gen.go
internal/integration/test_allof/oas_request_decoders_gen.go
internal/integration/test_allof/oas_request_encoders_gen.go
internal/integration/test_allof/oas_response_decoders_gen.go
internal/integration/test_allof/oas_response_encoders_gen.go
internal/integration/test_allof/oas_router_gen.go
internal/integration/test_allof/oas_schemas_gen.go
internal/integration/test_allof/oas_server_gen.go
internal/integration/test_allof/oas_unimplemented_gen.go
internal/integration/test_allof/oas_validators_gen.go
jsonschema/parser.go

Fixes https://github.com/ogen-go/ogen/issues/681#issuecomment-1320828474

refactor: better allof

---

Makefile
README.md
_testdata/positive/sample.json
gen/_template/schema/struct.tmpl
gen/ir/field.go
gen/ir/field_test.go
gen/schema_gen.go
gen/schema_gen_test.go
go.mod
internal/integration/sample_api/oas_faker_gen.go
internal/integration/sample_api/oas_json_gen.go
internal/integration/sample_api/oas_schemas_gen.go
internal/integration/sample_api_nc/oas_json_gen.go
internal/integration/sample_api_nc/oas_schemas_gen.go
internal/integration/sample_api_ns/oas_json_gen.go
internal/integration/sample_api_ns/oas_schemas_gen.go
internal/integration/sample_api_nsnc/oas_json_gen.go
internal/integration/sample_api_nsnc/oas_schemas_gen.go
jsonschema/parser.go
jsonschema/schema.go
openapi/parser/_testdata/remotes/api/pet-tags.yml
openapi/parser/parser_test.go

Implements https://github.com/ogen-go/ogen/issues/689
See usage in README.md

feat(gen): additional go struct field tags

---

gen/gen_operation.go
gen/gen_operation_test.go
openapi/parser/_testdata/negative/paths/path_refs_parameter_two_times.json
openapi/parser/_testdata/negative/paths/unknown_path_parameter.json
openapi/parser/parse_path_item.go
openapi/parser/parse_webhook.go
openapi/parser/parser.go
openapi/parser/path_parser.go
openapi/parser/path_parser_test.go
openapi/parser/resolve.go

feat(gen): warn about unused path parameters

---

_testdata/positive/http_responses.json
examples/ex_github/oas_response_decoders_gen.go
examples/ex_petstore/oas_response_decoders_gen.go
gen/_template/response_decode.tmpl
internal/integration/responses_test.go
internal/integration/test_http_responses/oas_client_gen.go
internal/integration/test_http_responses/oas_handlers_gen.go
internal/integration/test_http_responses/oas_response_decoders_gen.go
internal/integration/test_http_responses/oas_response_encoders_gen.go
internal/integration/test_http_responses/oas_router_gen.go
internal/integration/test_http_responses/oas_schemas_gen.go
internal/integration/test_http_responses/oas_server_gen.go
internal/integration/test_http_responses/oas_unimplemented_gen.go

fix(gen): do not require optional response headers

---

internal/integration/security_test.go
ogenerrors/ogenerrors.go

Seems more appropriate than 400.

Change security error HTTP status code to 401 Unauthorized

---

_testdata/positive/http_requests.json
examples/ex_2ch/oas_request_decoders_gen.go
gen/_template/request_decode.tmpl
internal/integration/requests_test.go
internal/integration/test_allof/oas_request_decoders_gen.go
internal/integration/test_form/oas_request_decoders_gen.go
internal/integration/test_http_requests/oas_client_gen.go
internal/integration/test_http_requests/oas_handlers_gen.go
internal/integration/test_http_requests/oas_request_decoders_gen.go
internal/integration/test_http_requests/oas_request_encoders_gen.go
internal/integration/test_http_requests/oas_response_decoders_gen.go
internal/integration/test_http_requests/oas_response_encoders_gen.go
internal/integration/test_http_requests/oas_router_gen.go
internal/integration/test_http_requests/oas_schemas_gen.go
internal/integration/test_http_requests/oas_server_gen.go
internal/integration/test_http_requests/oas_unimplemented_gen.go

fix(gen): define form decoder variable only if necessary

---

cmd/ogen/main.go
gen/generator.go
gen/options.go
openapi/api.go
openapi/parser/expand.go
openapi/parser/parse_server.go
openapi/parser/parser.go
openapi/parser/resolve_external_test.go
openapi/parser/resolve_test.go
openapi/server.go
security_scheme.go
spec.go

feat(parser): add `Expand` function

---

gen/schema_gen_sum.go
jsonschema/parser.go
jsonschema/parser_test.go
jsonschema/schema.go
openapi/parser/parser_test.go

fix(gen): properly merge required fields

---

examples/ex_2ch/oas_validators_gen.go
examples/ex_ent/oas_validators_gen.go
examples/ex_github/oas_validators_gen.go
examples/ex_manga/oas_validators_gen.go
examples/ex_openapi/output.gen.go
examples/ex_petstore/oas_validators_gen.go
gen/_template/validators.tmpl
internal/integration/sample_api/oas_validators_gen.go
internal/integration/sample_api_nc/oas_validators_gen.go
internal/integration/sample_api_ns/oas_validators_gen.go
internal/integration/sample_api_nsnc/oas_validators_gen.go
internal/integration/techempower/oas_validators_gen.go
internal/integration/test_http_responses/oas_validators_gen.go

fix(gen): convert alias type to original before validating

---

examples/ex_2ch/oas_faker_gen.go
examples/ex_github/oas_faker_gen.go
examples/ex_gotd/oas_faker_gen.go
examples/ex_telegram/oas_faker_gen.go
gen/_template/faker/faker.tmpl
gen/_template/faker/faker_sum.tmpl
internal/integration/sample_api/oas_faker_gen.go
internal/integration/test_anyof/oas_faker_gen.go

fix(gen): resolve a variable name conflict

---

gen/schema_gen_sum.go

fix(gen): merge `allOf`  subschemas recursively

---

jsonschema/parser.go

fix(jsonschema): allow `xml` property

---

_testdata/positive/sample.json
gen/schema_gen.go
internal/integration/sample_api/oas_client_gen.go
internal/integration/sample_api/oas_faker_gen.go
internal/integration/sample_api/oas_handlers_gen.go
internal/integration/sample_api/oas_json_gen.go
internal/integration/sample_api/oas_response_decoders_gen.go
internal/integration/sample_api/oas_response_encoders_gen.go
internal/integration/sample_api/oas_router_gen.go
internal/integration/sample_api/oas_schemas_gen.go
internal/integration/sample_api/oas_server_gen.go
internal/integration/sample_api/oas_test_examples_gen_test.go
internal/integration/sample_api/oas_unimplemented_gen.go
internal/integration/sample_api/oas_validators_gen.go
internal/integration/sample_api_nc/oas_handlers_gen.go
internal/integration/sample_api_nc/oas_json_gen.go
internal/integration/sample_api_nc/oas_response_encoders_gen.go
internal/integration/sample_api_nc/oas_router_gen.go
internal/integration/sample_api_nc/oas_schemas_gen.go
internal/integration/sample_api_nc/oas_server_gen.go
internal/integration/sample_api_nc/oas_unimplemented_gen.go
internal/integration/sample_api_nc/oas_validators_gen.go
internal/integration/sample_api_ns/oas_client_gen.go
internal/integration/sample_api_ns/oas_json_gen.go
internal/integration/sample_api_ns/oas_response_decoders_gen.go
internal/integration/sample_api_ns/oas_schemas_gen.go
internal/integration/sample_api_ns/oas_validators_gen.go
internal/integration/sample_api_nsnc/oas_json_gen.go
internal/integration/sample_api_nsnc/oas_schemas_gen.go
internal/integration/sample_api_nsnc/oas_validators_gen.go

- feat(gen): allow x-ogen-name for tuples
- chore(gen): commit

feat(gen): x-ogen-name for tuples

---

.golangci.yml
_testdata/positive/format_gen.json
conv/decode.go
conv/encode.go
examples/ex_test_format/oas_client_gen.go
examples/ex_test_format/oas_faker_gen.go
examples/ex_test_format/oas_handlers_gen.go
examples/ex_test_format/oas_json_gen.go
examples/ex_test_format/oas_parameters_gen.go
examples/ex_test_format/oas_request_decoders_gen.go
examples/ex_test_format/oas_request_encoders_gen.go
examples/ex_test_format/oas_response_decoders_gen.go
examples/ex_test_format/oas_response_encoders_gen.go
examples/ex_test_format/oas_router_gen.go
examples/ex_test_format/oas_schemas_gen.go
examples/ex_test_format/oas_server_gen.go
examples/ex_test_format/oas_unimplemented_gen.go
examples/ex_test_format/oas_validators_gen.go
gen/_template/validators.tmpl
gen/ir/json.go
gen/ir/template_helpers.go
gen/schema_gen_primitive.go
json/float.go
json/float_test.go
json/int.go
json/int_test.go
json/uint.go
json/uint_test.go
validate/float.go

feat(gen): support stringified floats

---

examples/ex_github/oas_faker_gen.go
examples/ex_github/oas_json_gen.go
examples/ex_github/oas_schemas_gen.go
examples/ex_github/oas_validators_gen.go
examples/ex_openapi/output.gen.go
gen/generics.go

fix(gen): properly handle aliased arrays

---

gen/schema_gen_sum.go

fix(gen): match `discriminator` mapping by ref

---

.github/workflows/image_build.yml
Dockerfile
README.md

This PR adds Dockerfile and job to build a Docker image for Ogen and push it to ghcr.
**Motivation:**
Have the ability to generate code in the container, to guarantee that it will be generated regardless of a local version of Ogen

feat: add docker image build

---

gen/gen_security.go

fix(gen): ignore security format case

---

examples/ex_2ch/oas_client_gen.go
examples/ex_firecracker/oas_client_gen.go
examples/ex_github/oas_client_gen.go
examples/ex_gotd/oas_client_gen.go
examples/ex_openai/oas_client_gen.go
examples/ex_telegram/oas_client_gen.go
examples/ex_test_format/oas_client_gen.go
examples/ex_tinkoff/oas_client_gen.go
gen/_template/client.tmpl
gen/_template/response_encode.tmpl
gen/features.go
gen/write.go
internal/integration/_config/allOf.yml
internal/integration/_config/sample_api.yml
internal/integration/sample_api/oas_response_encoders_gen.go
internal/integration/sample_api_no_otel/oas_client_gen.go
internal/integration/sample_api_no_otel/oas_response_decoders_gen.go
internal/integration/sample_api_ns/oas_client_gen.go
internal/integration/test_allof/oas_client_gen.go
internal/integration/test_form/oas_client_gen.go
internal/integration/test_http_requests/oas_client_gen.go

feat(gen): add feature to validate message before sending

---

gen/_template/response_encode.tmpl

fix(gen): add missing feature check

---

examples/ex_k8s/oas_response_decoders_gen.go
examples/ex_k8s/oas_response_encoders_gen.go
examples/ex_k8s/oas_schemas_gen.go
examples/ex_manga/oas_response_decoders_gen.go
examples/ex_manga/oas_response_encoders_gen.go
examples/ex_manga/oas_schemas_gen.go
gen/gen_responses.go
internal/integration/responses_test.go
internal/integration/test_http_responses/oas_client_gen.go
internal/integration/test_http_responses/oas_handlers_gen.go
internal/integration/test_http_responses/oas_response_decoders_gen.go
internal/integration/test_http_responses/oas_response_encoders_gen.go
internal/integration/test_http_responses/oas_schemas_gen.go
internal/integration/test_http_responses/oas_server_gen.go
internal/integration/test_http_responses/oas_unimplemented_gen.go

fix(gen): generate `ContentType` header for mask responses

---

.golangci.yml
examples/ex_2ch/oas_request_encoders_gen.go
examples/ex_openai/oas_request_encoders_gen.go
gen/_template/request_encode.tmpl
internal/integration/test_allof/oas_request_encoders_gen.go
internal/integration/test_form/oas_request_encoders_gen.go
internal/integration/test_http_requests/oas_request_encoders_gen.go
uri/query_encoder.go

fix(gen): set Content-Type for JSON-encoded form parameters

---

gen/schema_gen_sum.go

fix(gen): detect conflict when generic is not of the same base type

---

examples/ex_gotd/oas_defaults_gen.go
examples/ex_gotd/oas_faker_gen.go
examples/ex_gotd/oas_json_gen.go
examples/ex_gotd/oas_schemas_gen.go
examples/ex_gotd/oas_test_examples_gen_test.go
examples/ex_gotd/oas_validators_gen.go
examples/ex_telegram/oas_defaults_gen.go
examples/ex_telegram/oas_faker_gen.go
examples/ex_telegram/oas_json_gen.go
examples/ex_telegram/oas_schemas_gen.go
examples/ex_telegram/oas_test_examples_gen_test.go
examples/ex_telegram/oas_validators_gen.go
gen/schema_gen_sum.go
internal/integration/sample_api/oas_faker_gen.go
internal/integration/sample_api/oas_json_gen.go
internal/integration/sample_api/oas_schemas_gen.go
internal/integration/sample_api_nc/oas_json_gen.go
internal/integration/sample_api_nc/oas_schemas_gen.go
internal/integration/sample_api_no_otel/oas_json_gen.go
internal/integration/sample_api_no_otel/oas_schemas_gen.go
internal/integration/sample_api_ns/oas_json_gen.go
internal/integration/sample_api_ns/oas_schemas_gen.go
internal/integration/sample_api_nsnc/oas_json_gen.go
internal/integration/sample_api_nsnc/oas_schemas_gen.go

fix(gen): do not remove discriminator field

---

examples/ex_k8s/oas_router_gen.go
gen/_template/router.tmpl

fix(gen): properly handle intermediate route node

---

examples/ex_gotd/oas_faker_gen.go
examples/ex_gotd/oas_json_gen.go
examples/ex_gotd/oas_schemas_gen.go
examples/ex_gotd/oas_validators_gen.go
examples/ex_k8s/oas_faker_gen.go
examples/ex_k8s/oas_json_gen.go
examples/ex_k8s/oas_schemas_gen.go
examples/ex_k8s/oas_validators_gen.go
examples/ex_openapi/output.gen.go
examples/ex_telegram/oas_faker_gen.go
examples/ex_telegram/oas_json_gen.go
examples/ex_telegram/oas_schemas_gen.go
examples/ex_telegram/oas_validators_gen.go
gen/gen_schema.go
gen/generator.go
gen/generics.go
gen/ir/recursion.go
gen/ir/validation.go
internal/integration/test_naming_extensions/oas_json_gen.go

fix(ir): handle recursion in optional fields properly

---

_testdata/positive/servers.json
gen/_template/servers.tmpl
internal/integration/test_servers/oas_servers_gen.go

Allow server variable enum to be unset

---

gen/genfs/genfs.go
gen/schema_gen_sum_test.go
internal/integration/e2e_err_test.go
internal/integration/metrics_test.go
json/unix_str_test.go
json/unix_test.go
json/uuid.go
validate/errors.go

chore: run gofumpt

---

internal/integration/sample_api/oas_cfg_gen.go
internal/integration/sample_api/oas_json_gen.go
internal/integration/sample_api/oas_schemas_gen.go
internal/integration/sample_api_nc/oas_cfg_gen.go
internal/integration/sample_api_nc/oas_json_gen.go
internal/integration/sample_api_nc/oas_schemas_gen.go
internal/integration/sample_api_no_otel/oas_cfg_gen.go
internal/integration/sample_api_no_otel/oas_json_gen.go
internal/integration/sample_api_no_otel/oas_schemas_gen.go
internal/integration/sample_api_ns/oas_cfg_gen.go
internal/integration/sample_api_ns/oas_json_gen.go
internal/integration/sample_api_ns/oas_schemas_gen.go
internal/integration/sample_api_nsnc/oas_cfg_gen.go
internal/integration/sample_api_nsnc/oas_json_gen.go
internal/integration/sample_api_nsnc/oas_schemas_gen.go
ogenregex/ogenregex.go
ogenregex/ogenregex_test.go

fix(ogenregex): print ECMAScript regexp literals

---

gen/reduce.go

fix(gen): compare number validators properly

---

examples/ex_2ch/oas_router_gen.go
examples/ex_firecracker/oas_router_gen.go
examples/ex_github/oas_router_gen.go
examples/ex_k8s/oas_router_gen.go
examples/ex_manga/oas_router_gen.go
examples/ex_oauth2/oas_router_gen.go
examples/ex_openai/oas_router_gen.go
examples/ex_petstore/oas_router_gen.go
examples/ex_petstore_expanded/oas_router_gen.go
examples/ex_route_params/oas_router_gen.go
gen/_template/router.tmpl
internal/integration/sample_api/oas_router_gen.go
internal/integration/sample_api_nc/oas_router_gen.go
internal/integration/sample_api_no_otel/oas_router_gen.go
internal/integration/test_parameters/oas_router_gen.go

Closes: https://github.com/ogen-go/ogen/issues/1411

fix(gen): handle slashes in leaf path parameters

---

openapi/parser/_testdata/expand/info_tags.yaml
openapi/parser/expand_test.go
openapi/parser/parse_info.go
openapi/parser/parse_path_item_test.go
openapi/parser/parser.go
openapi/parser/resolve_external_test.go
openapi/parser/resolve_test.go

- fix typo in ogen.Info struct
- fix missing tags in expanded spec

fix info tags

---

examples/ex_openai/oas_request_decoders_gen.go
gen/_template/request_decode.tmpl

fix(gen): set default values when decoding forms

---

gen/schema_gen_primitive.go

This commit fixes an issue where the `validateEnumValues` would pre-emptively fail if the enum type was set and its type was not an integer.  Since string types are also supported, this update to the validation check ensures that this can be properly processed later.

fix: support string enum types in validation
