LICENSE
All contributors confirmed consent.
Changing license from MIT to [Apache v2](https://www.apache.org/licenses/LICENSE-2.0).
This will require approval of every contributor.
=> chore: change license to Apache

gen/schema_gen.go
Since I am not familiar with the package (yet), I am not sure if this enough to fix this. There are no tests yet for this case. 
Fix #88
=> fix(gen): prefix numeric response / request structs with "R"

json/uuid.go, json/uuid_test.go
```
name          old time/op    new time/op    delta
DecodeUUID-4     173ns ± 3%     148ns ±34%   -14.15%  (p=0.001 n=13+15)
EncodeUUID-4     182ns ± 8%      29ns ±18%   -84.11%  (p=0.000 n=13+15)
name          old speed      new speed      delta
DecodeUUID-4   220MB/s ± 3%   261MB/s ±26%   +18.39%  (p=0.001 n=13+15)
EncodeUUID-4   209MB/s ± 8%  1323MB/s ±16%  +532.72%  (p=0.000 n=13+15)
name          old alloc/op   new alloc/op   delta
DecodeUUID-4     48.0B ± 0%      0.0B       -100.00%  (p=0.000 n=15+15)
EncodeUUID-4     48.0B ± 0%      0.0B       -100.00%  (p=0.000 n=15+15)
name          old allocs/op  new allocs/op  delta
DecodeUUID-4      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=15+15)
EncodeUUID-4      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=15+15)
```
=> feat(json): optimize UUID encode/decode

examples/ex_ent/oas_schemas_gen.go, examples/ex_github/oas_schemas_gen.go, examples/ex_manga/oas_schemas_gen.go, examples/ex_petstore/oas_schemas_gen.go, gen/_template/schemas.tmpl, internal/ir/template_helpers.go
If the receiver of the methods to mark structs as responses do not need to have a pointer receiver because it would result in double pointers (slices are pointer types already).
This PR resolves that. Please do a thorough review, I don't know the codebase well enough yet to see all side effects.
=> feat(gen): methods do not have a pointer receiver

bench_test.go, examples/ex_firecracker/oas_json_gen.go, examples/ex_github/oas_json_gen.go, examples/ex_manga/oas_json_gen.go, examples/ex_telegram/oas_json_gen.go, examples/ex_tinkoff/oas_json_gen.go, gen/_template/json/encoders_enum.tmpl, gen/_template/json/encoders_generic.tmpl, internal/ir/primitive.go, internal/sample_api/oas_json_gen.go
Benchstat result:
```
name                           old time/op    new time/op    delta
JSON/Sample/PetType/Decode-12    25.8ns ± 1%    13.4ns ± 1%   -48.25%  (p=0.000 n=15+14)
name                           old speed      new speed      delta
JSON/Sample/PetType/Decode-12   232MB/s ± 1%   449MB/s ± 0%   +93.33%  (p=0.000 n=15+13)
name                           old alloc/op   new alloc/op   delta
JSON/Sample/PetType/Decode-12     4.00B ± 0%     0.00B       -100.00%  (p=0.000 n=15+15)
name                           old allocs/op  new allocs/op  delta
JSON/Sample/PetType/Decode-12      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=15+15)
```
=> fix(gen): use constants for enum values to prevent allocations

examples/ex_ent/oas_client_gen.go, examples/ex_ent/oas_req_enc_gen.go, examples/ex_firecracker/oas_client_gen.go, examples/ex_firecracker/oas_req_enc_gen.go, examples/ex_github/oas_client_gen.go, examples/ex_github/oas_req_enc_gen.go, examples/ex_gotd/oas_client_gen.go, examples/ex_gotd/oas_req_enc_gen.go, examples/ex_telegram/oas_client_gen.go, examples/ex_telegram/oas_req_enc_gen.go, examples/ex_tinkoff/oas_client_gen.go, examples/ex_tinkoff/oas_req_enc_gen.go, gen/_template/client.tmpl, gen/_template/req_enc.tmpl, internal/ir/operation.go, internal/sample_api/oas_client_gen.go, internal/sample_api/oas_req_enc_gen.go, internal/sample_err/oas_client_gen.go, internal/sample_err/oas_req_enc_gen.go
Encoder still allocates bytes.Reader, however allocating a small struct is better
rather than allocating large buffer with encoded JSON
Fixes #123.
=> fix(gen): do not copy body twice

_testdata/sample.json, e2e_test.go, gen/_template/router.tmpl, internal/sample_api/oas_client_gen.go, internal/sample_api/oas_handlers_gen.go, internal/sample_api/oas_interfaces_gen.go, internal/sample_api/oas_param_dec_gen.go, internal/sample_api/oas_param_gen.go, internal/sample_api/oas_res_dec_gen.go, internal/sample_api/oas_res_enc_gen.go, internal/sample_api/oas_router_gen.go, internal/sample_api/oas_schemas_gen.go, internal/sample_api/oas_server_gen.go, router_test.go
For a scheme with defined routes like:
```
/parent/{param}
/parent/{param}/child
```
it is not possible to retrieve the parameter just by finding the index
of tail (/), because its absence is anticipated. If there is no
corresponding tail in the route element, it means a route with a
dangling parameter.
=> fix(gen): match parent/{param}/child routes

_testdata/positive/pokemon-api.json, internal/ir/type.go
Prevent panic in boxing cases like "array of Any"
=> fix(ir): do not panic, if generating postfix for Any type

jsonpointer/jsonpointer.go, jsonpointer/jsonpointer_test.go
```
name       old time/op    new time/op    delta
Resolve-4    4.52µs ± 3%    3.68µs ± 3%   -18.54%  (p=0.000 n=14+14)
name       old alloc/op   new alloc/op   delta
Resolve-4      256B ± 0%        0B       -100.00%  (p=0.000 n=15+15)
name       old allocs/op  new allocs/op  delta
Resolve-4      18.0 ± 0%       0.0       -100.00%  (p=0.000 n=15+15)
```
=> feat(jsonpointer): improve escaping, reduce allocations

json/std_duration.go, json/time.go, json/time_test.go
Benchstat result:
```
name              old time/op    new time/op    delta
EncodeDuration-4     106ns ± 7%      69ns ± 2%   -35.36%  (p=0.000 n=15+15)
name              old alloc/op   new alloc/op   delta
EncodeDuration-4     16.0B ± 0%      0.0B       -100.00%  (p=0.000 n=15+15)
name              old allocs/op  new allocs/op  delta
EncodeDuration-4      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=15+15)
```
=> feat(json): make Duration encoder allocation-free

json/int.go, json/int_test.go
Benchstat comparison:
```
name                 old time/op    new time/op    delta
DecodeStringInt32-4    96.3ns ± 2%    55.0ns ± 1%   -42.87%  (p=0.000 n=14+15)
DecodeStringInt64-4    97.1ns ± 2%    52.5ns ± 1%   -45.89%  (p=0.000 n=14+15)
name                 old alloc/op   new alloc/op   delta
DecodeStringInt32-4     16.0B ± 0%      0.0B       -100.00%  (p=0.000 n=15+15)
DecodeStringInt64-4     16.0B ± 0%      0.0B       -100.00%  (p=0.000 n=15+15)
name                 old allocs/op  new allocs/op  delta
DecodeStringInt32-4      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=15+15)
DecodeStringInt64-4      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=15+15)
```
=> feat(json): reduce string int decoding allocations

jsonpointer/jsonpointer.go, jsonpointer/jsonpointer_test.go
Benchstat result:
```
name       old time/op    new time/op    delta
Resolve-4    3.64µs ± 2%    3.27µs ± 2%  -10.03%  (p=0.000 n=14+15)
```
=> feat(jsonpointer): use jx iterator API to return early

middleware/middleware.go, middleware/middleware_test.go
Benchstat:
```
name                old time/op    new time/op    delta
ChainMiddlewares-4    2.69µs ± 2%    1.29µs ± 2%  -52.01%  (p=0.000 n=13+15)
name                old alloc/op   new alloc/op   delta
ChainMiddlewares-4    1.57kB ± 0%    0.48kB ± 0%  -69.39%  (p=0.000 n=15+15)
name                old allocs/op  new allocs/op  delta
ChainMiddlewares-4      39.0 ± 0%      20.0 ± 0%  -48.72%  (p=0.000 n=15+15)
```
=> perf(middleware): reduce chain allocation

gen/_template/header.tmpl
Benchstat result of `manga.json` generation:
```
name         old time/op    new time/op    delta
Generator-4     135ms ± 3%      74ms ± 3%  -45.22%  (p=0.000 n=14+15)
name         old alloc/op   new alloc/op   delta
Generator-4    10.1MB ± 0%     9.2MB ± 0%   -9.45%  (p=0.000 n=14+15)
name         old allocs/op  new allocs/op  delta
Generator-4      281k ± 0%      262k ± 0%   -6.55%  (p=0.000 n=15+15)
```
=> perf(gen): add mime packages to header

gen/gen_schema.go, gen/write.go, gen_bench_test.go
Benchstat:
```
name                        old time/op    new time/op    delta
Generator/api.github.com-4     7.41s ± 1%     4.29s ± 2%  -42.16%  (p=0.000 n=24+22)
Generator/gotd_bot_api-4       1.24s ± 2%     0.86s ± 5%  -30.10%  (p=0.000 n=22+25)
Generator/tinkoff-4            258ms ± 3%     153ms ± 3%  -40.57%  (p=0.000 n=24+24)
Generator/manga-4             77.7ms ± 3%    39.6ms ± 4%  -49.04%  (p=0.000 n=25+24)
name                        old alloc/op   new alloc/op   delta
Generator/api.github.com-4    1.22GB ± 0%    1.24GB ± 0%   +1.72%  (p=0.000 n=24+23)
Generator/gotd_bot_api-4       191MB ± 0%     193MB ± 0%   +0.95%  (p=0.000 n=23+25)
Generator/tinkoff-4           35.3MB ± 0%    36.5MB ± 4%   +3.24%  (p=0.000 n=25+25)
Generator/manga-4             9.19MB ± 0%    9.45MB ± 3% …
```
=> perf(gen): run generation in parallel

gen/ir/description.go, gen/ir/description_test.go, gen/ir/json.go, gen/ir/template_helpers.go, gen/ir/type.go, gen/names.go, gen/schema_gen.go, gen/templates.go, internal/naming/capitalize.go, internal/naming/naming.go, internal/naming/rules.go, internal/naming/rules_test.go
Performance of `strings.ToLower` + hashmap is much better than linear search, binary search
and B-Tree because of slow string comparison.
```
name                 time/op
Rule/Rule-4          56.3ns ± 2%
Rule/LinearSearch-4   394ns ± 2%
```
=> perf(naming): use hashmap to search naming rules

examples/ex_k8s/oas_handlers_gen.go, examples/ex_tinkoff/oas_handlers_gen.go, gen/_template/handlers.tmpl, internal/integration/sample_api/oas_handlers_gen.go, internal/integration/sample_api_nc/oas_handlers_gen.go
Close: https://github.com/ogen-go/ogen/issues/662
=> handlers: fixed duplicated variable

gen/schema_gen.go
This PR fixes faulty generator warnings when generating the code for `number` and `integer` types declared in the input YAML.
The example of input YAML: 
```yaml
... 
ratio:
description: The ratio of something.
type: number
minimum: 0
maximum: 1
total:
description: The total of something.
type: integer
minimum: 0
...
```
results in the following warnings:
```
WARN	schemagen	Float validator cannot be applied to generated type and will be ignored	{"at": "file:///somefile.yml:xx:xx", "type": "number", "format": "", "go_type": "float64"}
WARN	schemagen	Int validator cannot be applied to generated type and will be ignored	{"at": "file:///somefile.yaml:xx:xx", "type": "integer", "format": "", "go_type": "int"}
```
=> fix(gen): avoid faulty warnings for `number` and `integer` types

examples/ex_github/oas_schemas_gen.go, examples/ex_k8s/oas_schemas_gen.go, examples/ex_manga/oas_schemas_gen.go, gen/_template/schema/stream.tmpl, internal/integration/sample_api/oas_schemas_gen.go, internal/integration/sample_api_nc/oas_schemas_gen.go, internal/integration/sample_api_ns/oas_schemas_gen.go, internal/integration/sample_api_nsnc/oas_schemas_gen.go, internal/integration/test_http_requests/oas_schemas_gen.go, internal/integration/test_http_responses/oas_schemas_gen.go
The current implementation of the templated stream response `Read(byte[])` function uses the `Data io.Reader` field without first checking for `nil`.
Users who want to return a value with an empty body are forced to explicitly specify an empty `io.Reader` rather than simply ignore the field and get use from the empty struct.
This commit adds a `nil` check before using the `Data` field and, if it is `nil`, responds as if it were an empty `io.Reader` instead of panicking.
This will hopefully make this library slightly more ergonomic to use.
=> feat(gen): no NPE on default stream responses

jsonschema/parser.go
This appears to be an openapi extension to jsonschema, but without this the parsing fails unnecessarily.
https://swagger.io/docs/specification/data-models/representing-xml/
=> fix(gen): allow xml property for arrays and objects

.golangci.yml, gen/generator.go, gen/genfs/genfs.go, gen/write.go, tools/mkformattest/main.go
This commit updates the file permissions in the various `os.WriteFile` calls from `600` -> `644`, as there isn't a good reason to make the files readable only to the user who generates them. This change requires updating the G306 rule in the gosec linter, which seems to be restrictive as a way to prevent leaking secrets in files that are created by Go code. As the code being generated won't contain secrets (by design), this isn't an issue and it should be safe to allow all users to read the generated files by default.
Note that this change will not alter the generated code in any way. It only affects the permissions on the files containing the generated code.
=> fix(gen): generate files with read permissions for all users

uri/query_param_decoder.go, uri/query_param_decoder_test.go, uri/query_param_encoder_test.go
Given the schema below,
```yaml
/resource:
get:
parameters:
- name: my_enums
in: query
required: true
type: array
items:
type: string
enum:
- a
- b
```
hitting the generated ogen server API using the generated ogen client with an empty array raises validation error, because the client encodes `[]MyEnums{}` into `/resource?my_eums=` then the server tries to enum-validate against the net/url decoded value `[]string{""}`.
This PR attempts to fix this by making array decoder not call the child decoder for `[]string{""}`.
Seems to me like the spec doesn't clearly state about this empty array case:
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#style-examples
found a stackoverflow question without answer:
https://stackoverflow.com/questions/74589019/openapi-empty-array- …
=> Fix logic for decoding valueless query parameter into an array

examples/ex_firecracker/oas_json_gen.go, examples/ex_github/oas_json_gen.go, examples/ex_gotd/oas_json_gen.go, examples/ex_k8s/oas_json_gen.go, examples/ex_openai/oas_json_gen.go, examples/ex_openapi/output.gen.go, examples/ex_telegram/oas_json_gen.go, examples/ex_test_format/oas_json_gen.go, examples/ex_tinkoff/oas_json_gen.go, gen/_template/json/encoders_struct.tmpl, internal/integration/sample_api/oas_json_gen.go, internal/integration/sample_api_nc/oas_json_gen.go, internal/integration/sample_api_ns/oas_json_gen.go, internal/integration/sample_api_nsnc/oas_json_gen.go
Fixes #955 
With this change, the following complaint when running `go vet` will be resolved.
```
internal/integration/sample_api_nsnc/oas_json_gen.go:2213:3: unreachable code                      <
internal/integration/sample_api_nsnc/oas_json_gen.go:4047:3: unreachable code                      <
internal/integration/sample_api_nsnc/oas_json_gen.go:4772:3: unreachable code                      <
internal/integration/sample_api_nc/oas_json_gen.go:2213:3: unreachable code                        <
internal/integration/sample_api_nc/oas_json_gen.go:4047:3: unreachable code                        <
internal/integration/sample_api_nc/oas_json_gen.go:4772:3: unreachable code                        <
internal/integration/sample_api_ns/oas_json_gen.go:2213:3: unreachable code …
```
=> fix(gen): remove unreachable code

examples/ex_gotd/oas_schemas_gen.go, examples/ex_telegram/oas_schemas_gen.go, gen/_template/schema/sum.tmpl, gen/ir/type.go, internal/integration/sample_api/oas_schemas_gen.go, internal/integration/sample_api_nc/oas_schemas_gen.go, internal/integration/sample_api_ns/oas_schemas_gen.go, internal/integration/sample_api_nsnc/oas_schemas_gen.go
Closes: https://github.com/ogen-go/ogen/issues/967
Just changing the generated string constant
This won't allow us to use the same value as was stated in https://github.com/ogen-go/ogen/issues/967#issue-1787529410.
Please tell me if any changes to be made are missing.
=> fix(gen): use mapping key for discriminator const

.github/workflows/image_build.yml
Hey, I've saw that image build failed, check the reason and found that I've made invalid image name and version concatenation in #1001.
I've tested those changes on my repository, and with those changes everything will work in a proper way
=> ci: fix image build

uri/header_param_encoder.go, uri/header_param_encoder_test.go
This PR adds a special case for encoding `Set-Cookie` headers in responses. Specifically, it prevents `headerParamEncoder` from folding multiple header values into a single header value using a comma separator, as per [RFC6265](https://datatracker.ietf.org/doc/html/rfc6265):
>   Origin servers SHOULD NOT fold multiple `Set-Cookie` header fields into a single header field.  The usual mechanism for folding HTTP headers fields (i.e., as defined in [RFC2616 section 4.2](https://www.rfc-editor.org/rfc/rfc2616#section-4.2)) might change the semantics of the `Set-Cookie` header field because the `%x2C` (`,`) character is used by `Set-Cookie` in a way that conflicts with such folding.
The comma mentioned by the RFC appears when using a cookie with an expiry timestamp, because the recommended …
=> fix: do not fold Set-Cookie values into a single header, per RFC6265

examples/ex_k8s/oas_security_gen.go, examples/ex_oauth2/oas_security_gen.go, examples/ex_tinkoff/oas_security_gen.go, gen/_template/security.tmpl, internal/integration/sample_api/oas_security_gen.go, internal/integration/sample_api_nc/oas_security_gen.go, internal/integration/test_security/oas_security_gen.go, ogenerrors/security.go
Added option to exclude security requirement for handlers.
This is useful in case you want to have multiple security providers with the same data.
For an example if you want to use both `apikey` and `oauth` security providers on one endpoint you want to check structure of a token first. If it starts with Bearer you want to skip bearer validation and just enforce the oauth validation.
=> feat(security): added option to exclude sec requirement 

examples/ex_2ch/oas_validators_gen.go, examples/ex_firecracker/oas_validators_gen.go, examples/ex_github/oas_validators_gen.go, examples/ex_gotd/oas_validators_gen.go, examples/ex_k8s/oas_validators_gen.go, examples/ex_manga/oas_validators_gen.go, examples/ex_openai/oas_validators_gen.go, examples/ex_openapi/output.gen.go, examples/ex_petstore/oas_validators_gen.go, examples/ex_telegram/oas_validators_gen.go, examples/ex_test_format/oas_validators_gen.go, examples/ex_tinkoff/oas_validators_gen.go, gen/_template/validators.tmpl, internal/integration/sample_api/oas_validators_gen.go, internal/integration/sample_api_nc/oas_validators_gen.go, internal/integration/sample_api_ns/oas_validators_gen.go, internal/integration/sample_api_nsnc/oas_validators_gen.go, internal/integration/test_allof/oas_validators_gen.go, internal/integration/test_anyof/oas_validators_gen.go, internal/integration/test_enum_naming/oas_validators_gen.go, internal/integration/test_form/oas_validators_gen.go, internal/integration/test_http_responses/oas_validators_gen.go, internal/integration/test_parameters/oas_validators_gen.go, validate/error.go
When use Validate() in handler, if handler takes nil - we have panic
=> feat(validate): add check receiver pointer

examples/ex_test_format/oas_client_gen.go, examples/ex_test_format/oas_faker_gen.go, examples/ex_test_format/oas_handlers_gen.go, examples/ex_test_format/oas_json_gen.go, examples/ex_test_format/oas_request_decoders_gen.go, examples/ex_test_format/oas_request_encoders_gen.go, examples/ex_test_format/oas_response_decoders_gen.go, examples/ex_test_format/oas_response_encoders_gen.go, examples/ex_test_format/oas_schemas_gen.go, examples/ex_test_format/oas_server_gen.go, examples/ex_test_format/oas_unimplemented_gen.go, gen/ir/type.go
=> fix(ir): properly handle stringified optionals

gen/tstorage.go
I initially thought that automatically generating wrapper types would be nice (https://github.com/ogen-go/ogen/issues/937), and I still think that it would, but I also now realize that it's much harder than I anticipated, at least for me with my limited knowledge of the repo/codegen flow. Using this I was able to know when I would need to wrap types with new names, but I wasn't able to figure out how to wire them up correctly to the operations so that they got generated out. And that's not even mentioning that we'd probably want to deduplicate them at some later point
This alone seems like a good start though, as it at least notifies us that there is a conflict. My specific issue was with a custom Date type that was not required, so it became OptDate just like another date field that was …
=> fix: detect conflict when generic is not of the same base type

openapi/parser/_testdata/negative/version/swagger.json, openapi/parser/version.go, spec.go, spec_test.go
Prettier error outup in case of swagger file/version. 
Before it returned Atoi parsing error because it was fed an empty string.
=> fix(validation): prettier error in case of swagger file

_testdata/positive/format_gen.json, conv/decode.go, conv/encode.go, examples/ex_test_format/oas_client_gen.go, examples/ex_test_format/oas_faker_gen.go, examples/ex_test_format/oas_handlers_gen.go, examples/ex_test_format/oas_json_gen.go, examples/ex_test_format/oas_parameters_gen.go, examples/ex_test_format/oas_request_decoders_gen.go, examples/ex_test_format/oas_request_encoders_gen.go, examples/ex_test_format/oas_response_decoders_gen.go, examples/ex_test_format/oas_response_encoders_gen.go, examples/ex_test_format/oas_router_gen.go, examples/ex_test_format/oas_schemas_gen.go, examples/ex_test_format/oas_server_gen.go, examples/ex_test_format/oas_unimplemented_gen.go, examples/ex_test_format/oas_validators_gen.go, gen/ir/faker.go, gen/ir/json.go, gen/ir/primitive.go, gen/ir/template_helpers.go, gen/schema_gen_primitive.go, json/mac.go, json/mac_test.go
Very simple PR that adds a new string primitive `mac` to be interpreted as a `net.HardwareAddr`, just like `ip` -> `netip.Addr`.
Marking as draft as I haven't added any integration test for the generator. I wonder where that should go. Should I create a new spec in the `_testdata` folder or add to an existing one? Also not suer about the `Array` functions. Those exist for the `UUID` primitive but not for e.g. the `IP` one? Why is that?
Anything I need to keep in mind?
If I can get this landed, I'll send a PR to the docs repo, as well.
Cheers!
=> feat: add 'mac' primitive for 'net.HardwareAddr' (MAC)

_testdata/positive/issue1182.yaml, gen/gen_responses.go, gen/genctx.go, gen/tstorage.go
=> fix(gen): use response ref as key for wrapped type lookup

cmd/ogen/main.go, gen/errors.go, gen/schema_gen_sum.go, location/error.go, location/file.go, location/print.go
=> feat(gen): improve discriminator inference error reporting

gen/templates.go, internal/integration/test_form/oas_request_decoders_gen.go, internal/integration/test_parameters/oas_parameters_gen.go
The code generated for `uri.QueryParameterObjectField` currently lacks field keys, leading to `go vet` flagging errors as shown below:
```bash
$ go vet ./...
internal/integration/test_form/oas_request_decoders_gen.go:455:46: github.com/ogen-go/ogen/uri.QueryParameterObjectField struct literal uses unkeyed fields
internal/integration/test_form/oas_request_decoders_gen.go:455:62: github.com/ogen-go/ogen/uri.QueryParameterObjectField struct literal uses unkeyed fields
internal/integration/test_form/oas_request_decoders_gen.go:477:46: github.com/ogen-go/ogen/uri.QueryParameterObjectField struct literal uses unkeyed fields
internal/integration/test_form/oas_request_decoders_gen.go:477:62: github.com/ogen-go/ogen/uri.QueryParameterObjectField struct literal uses unkeyed fields …
```
=> fix(gen): use named key in QueryParameterObjectField

gen/gen_responses.go
=> fix(gen): properly handle named response with multiple contents

examples/ex_gotd/oas_json_gen.go, examples/ex_telegram/oas_json_gen.go, gen/_template/json/encoders_struct.tmpl, gen/_template/json/encoders_sum.tmpl, gen/ir/json.go, internal/integration/json_test.go, internal/integration/sample_api/oas_json_gen.go, internal/integration/sample_api_nc/oas_json_gen.go, internal/integration/sample_api_no_otel/oas_json_gen.go, internal/integration/sample_api_ns/oas_json_gen.go, internal/integration/sample_api_nsnc/oas_json_gen.go
=> fix(gen): encode discriminator field only once

_testdata/positive/parameters.json, examples/ex_2ch/oas_request_encoders_gen.go, examples/ex_github/oas_client_gen.go, examples/ex_oauth2/oas_client_gen.go, examples/ex_petstore_expanded/oas_client_gen.go, gen/_template/json/encode.tmpl, gen/_template/uri/encode.tmpl, internal/integration/parameters_test.go, internal/integration/test_form/oas_request_encoders_gen.go, internal/integration/test_parameters/oas_client_gen.go, internal/integration/test_parameters/oas_handlers_gen.go, internal/integration/test_parameters/oas_parameters_gen.go, internal/integration/test_parameters/oas_response_decoders_gen.go, internal/integration/test_parameters/oas_response_encoders_gen.go, internal/integration/test_parameters/oas_router_gen.go, internal/integration/test_parameters/oas_server_gen.go, internal/integration/test_parameters/oas_unimplemented_gen.go
=> fix(gen): properly encode optional array parameter

_testdata/examples/api.github.com.json, examples/ex_github/oas_parameters_gen.go, examples/ex_github/oas_schemas_gen.go, examples/ex_github/oas_validators_gen.go, gen/gen_parameters.go, gen/genctx.go, gen/tstorage.go
=> fix(gen): re-use parameter type

examples/ex_oauth2/oas_security_gen.go, gen/_template/security.tmpl
If you have an OpenAPI spec that defines more than one oauth2 security scheme, the will each generate an `oauth2Scopes` variable in oas_security_gen.go, and the duplicate variable names will not compile. 
This fixes the issue by appending the unique name of the security scheme to the variable name so there will not be a conflict.
=> Fix duplicate variable name with multiple oauth2 security schemes

gen/schema_gen_sum.go
We have a bunch of objects we merge using `allOf` where both have the exact same value for `additionalProperties`, however we get the following error:
```
Feature "allOf additionalProperties merging" is not implemented yet.
```
This PR adds support for merging if both items are equal.
=> feat: Support allOf additionalProperties merging if both are the equal

internal/integration/all_of_test.go, jsonschema/parser.go, validate/errors.go, validate/string.go
This change includes the `Regex` when returning a `NoRegexMatchError` so clients have an easier time understanding any errors they encounter.
=> feat: include Pattern when encountering NoRegexMatchError

.github/workflows/ci.yml, Dockerfile
=> ci(Dockerfile): add Go SDK to resulting image

gen/reduce.go
=> fix(gen): ignore description and examples during convenient errors detection

examples/ex_github/oas_schemas_gen.go, examples/ex_openai/oas_schemas_gen.go, examples/ex_test_format/oas_schemas_gen.go, gen/_template/schema/generic.tmpl, internal/integration/sample_api/oas_schemas_gen.go, internal/integration/sample_api_nc/oas_schemas_gen.go, internal/integration/sample_api_no_otel/oas_schemas_gen.go, internal/integration/sample_api_ns/oas_schemas_gen.go, internal/integration/sample_api_nsnc/oas_schemas_gen.go, internal/integration/test_allof/oas_schemas_gen.go, internal/integration/test_http_responses/oas_schemas_gen.go
Hello team, 👋
Thank you for developing and maintaining this OSS!
Generated comments for methods had mismatched names, which could cause confusion.
This PR updates the comments to correctly reflect the actual method names (IsNull and SetToNull).
- Fixed IsSet → IsNull in the comment.
- Fixed SetNull → SetToNull in the comment.
This change improves code clarity and maintainability by ensuring that comments accurately describe the corresponding methods.
=> Fix generated comments to match method names

examples/ex_2ch/oas_parameters_gen.go, examples/ex_github/oas_parameters_gen.go, examples/ex_k8s/oas_response_decoders_gen.go, examples/ex_manga/oas_parameters_gen.go, examples/ex_manga/oas_response_decoders_gen.go, examples/ex_test_format/oas_parameters_gen.go, examples/ex_tinkoff/oas_parameters_gen.go, gen/_template/parameter_decode.tmpl, gen/_template/response_decode.tmpl, internal/integration/responses_test.go, internal/integration/sample_api/oas_parameters_gen.go, internal/integration/sample_api_nc/oas_parameters_gen.go, internal/integration/sample_api_no_otel/oas_parameters_gen.go, internal/integration/techempower/oas_parameters_gen.go, internal/integration/test_client_options/oas_parameters_gen.go, internal/integration/test_http_responses/oas_parameters_gen.go, internal/integration/test_http_responses/oas_response_decoders_gen.go, internal/integration/test_parameters/oas_parameters_gen.go, internal/integration/test_time_extension/oas_parameters_gen.go, internal/integration/test_webhooks/oas_parameters_gen.go, uri/cookie_decoder.go, uri/cookie_decoder_test.go, uri/header_decoder.go, uri/header_decoder_test.go, uri/query_decoder.go, uri/query_decoder_test.go, validate/errors.go
This PR is comprised of three changes.
Firstly, we introduce 3 new Errors in `errors.go`:
```go
// ErrQueryParamRequired reports that a query parameter is required, but not found.
var ErrQueryParamRequired = errors.New("query parameter required")
// ErrHeaderParamRequired reports that a header parameter is required, but not found.
var ErrHeaderParamRequired = errors.New("header parameter required")
// ErrCookieParamRequired reports that a cookie parameter is required, but not found.
var ErrCookieParamRequired = errors.New("cookie parameter required")
```
Secondly in all the below methods:
* `(d *QueryDecoder) HasParam(...)`
* `(d *HeaderDecoder) HasParam(...)`
* `(d *CookieDecoder) HasParam(...)`
...we return a `validate.Error` rather than an `errors.Errorf`. 
This provides a better …
=> fix: `HasParam` returns `Err(Query|Header|Cookie)ParamRequred` including `qparam` / `cfg.Name`

gen/_template/uri.tmpl, gen/_template/uri/decode.tmpl, gen/_template/uri/encode.tmpl, gen/_template/uri/encoders_map.tmpl, gen/write.go, internal/integration/test_additionalpropertiespatternproperties/oas_uri_gen.go
=> fix(gen): properly handle `ir.Map` when generating parameter encoders

examples/_config/example_all.yml
Without this change, example produces the following error:
```
load config:
main.run
/home/patrick/go/pkg/mod/github.com/ogen-go/ogen@v1.12.0/cmd/ogen/main.go:366
- compile path regex "*":
github.com/ogen-go/ogen/gen.(*Filters).UnmarshalYAML
/home/patrick/go/pkg/mod/github.com/ogen-go/ogen@v1.12.0/gen/options.go:287
- error parsing regexp: missing argument to repetition operator: `*`
```
=> docs: fix example in path_regex

ogenregex/convert.go, ogenregex/ogenregex_test.go
Fix #1466 
Go's regexp supports `\p{...}` and `\P{...}`, so `ogenregex.Convert` function should keep these formats in regexp pattern.
This patch doesn't check actual properties because supported properties depend on Go version.
e.g. Go v1.25 supports more properties: https://github.com/golang/go/issues/70780
=> fix(ogenregex): Support `\p{...}` and `\P{...}` format for Go regexp

_testdata/positive/additionalPropertiesPatternProperties.yml, uri/query_param_decoder.go, uri/query_param_decoder_test.go
When providing `patternProperties` for a `GET` request, the `query_param_decoder.DecodeFields` method does not appropriately consider the presence of free-formed fields (i.e. `patternProperties` and `additionalProperties`). 
This PR adjusts the `deepObject` handling to ensure that this is handled correctly.
=> fix: parse patternproperties correctly when handling query parameters

gen/nullable_oneof_test.go, gen/schema_gen_sum.go
One of the differences between OpenAPI 3.1 and 3.0 is how nullable
values are represented:
In 3.0, they are maked with `nullable: true`, and ogen handles that.
In 3.1, there are two ways:
- json schema type arrays for primitives:
```yaml
type:
- "string"
- "null"
```
- oneOf with a null alternative for other things (including
primitives):
```yaml
oneOf:
- type: "string"
- type: "null"
```
This commits adds special hadling for latter to unlock openapi 3.1
compatible specs to be handled by ogen.
Type array support is needed for for openapi 3.1 compatability, but this
is a first step that unlocks at least some 3.1 specs to be handled by
ogen.
=> feat: handle nullable oneOf

_testdata/positive/oneOf_single.json, gen/schema_transform.go, gen/schema_transform_test.go
While https://github.com/ogen-go/ogen/pull/1498 fixed https://github.com/ogen-go/ogen/issues/1442, it also caused `ogen` to stop generating sum types for single-value `oneOf`s with discriminator, which had previously been generated correctly anyway.
=> fix: generate sum type for single-value oneOf with discriminator

gen/ir/responses.go
Previously, responses with no status code and the same content type were ordered randomly.
=> Make response order stable
